server {
    listen 80;
    listen [::]:80;
    server_name ggo.kvicloud.ru;

    root /var/www/gungloryonline;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /downloads/ {
        autoindex off;
        add_header Cache-Control "public, max-age=300";
        try_files $uri =404;
    }

    location /content/ {
        add_header Cache-Control "public, max-age=60";
        try_files $uri =404;
    }

    location ~* \.(exe|AppImage|zip)$ {
        add_header Content-Disposition "attachment";
        add_header X-Content-Type-Options "nosniff";
    }
}
