package arena.client.ui;

import arena.client.net.ArenaClientNetwork;
import arena.client.net.ArenaClientShopItem;
import arena.client.net.ClientShopStore;
import arena.client.net.ClientSnapshotStore;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import org.lwjgl.glfw.GLFW;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

final class MatchShopScreen extends Screen {
    private static final String[] CATEGORIES={"PISTOL","RIFLE","HEAVY"};
    private static final Set<String> HIDDEN=Set.of(
        "gunnerarena:p9","gunnerarena:px18","gunnerarena:pdw50","gunnerarena:vector_x","gunnerarena:vkr47","gunnerarena:arx3","gunnerarena:raven_m96","gunnerarena:titan_50","jeg:spectre_dmr","jeg:double_barrel_shotgun");
    private final List<ArenaButton> buttons=new ArrayList<>();private final List<RowHit> rowHits=new ArrayList<>();
    private String category="PISTOL";private int selectedIndex,page;private long seen=-1;
    MatchShopScreen(){super(Component.literal("Оружие"));}
    @Override protected void init(){ArenaClientNetwork.requestSnapshot();ArenaClientNetwork.requestCatalog();rebuild();}
    private void rebuild(){for(ArenaButton b:buttons)removeWidget(b);buttons.clear();rowHits.clear();UiLayout.Rect p=panel();int pad=10,cy=p.y()+30,avail=p.width()-pad*2-(CATEGORIES.length-1)*5,cw=avail/CATEGORIES.length,cx=p.x()+pad;for(String c:CATEGORIES){final String v=c;buttons.add(addRenderableWidget(new ArenaButton(new UiLayout.Rect(cx,cy,cw,18),Component.literal(label(c)),q->{category=v;page=0;selectedIndex=0;rebuild();})));cx+=cw+5;}Layout l=layout(p);List<ArenaClientShopItem> f=filtered();if(selectedIndex>=f.size())selectedIndex=Math.max(0,f.size()-1);int maxPage=Math.max(0,(f.size()-1)/Math.max(1,l.rows));page=Math.max(0,Math.min(page,maxPage));int start=page*l.rows;for(int i=0;i<l.rows&&start+i<f.size();i++){int idx=start+i;UiLayout.Rect rr=new UiLayout.Rect(l.listX,l.listY+i*l.rowH,l.listW,l.rowH-2);buttons.add(addRenderableWidget(new ArenaButton(rr,Component.empty(),q->{selectedIndex=idx;rebuild();})));rowHits.add(new RowHit(rr,idx));}if(!f.isEmpty()){ArenaClientShopItem it=f.get(Math.min(selectedIndex,f.size()-1));var s=ClientSnapshotStore.get();boolean afford=s.roundCredits()>=it.price();ArenaButton buy=new ArenaButton(new UiLayout.Rect(l.detailX,l.buyY,l.detailW,20),Component.literal(!it.available()?"× НЕДОСТУПНО":(!afford?"◇ НУЖНО $":"✓ КУПИТЬ  $"+it.price())),q->ArenaClientNetwork.buy(it.id()));buy.active=it.available()&&afford&&UiAccessPolicy.canShop(s,ClientSnapshotStore.fresh(System.currentTimeMillis()));buttons.add(addRenderableWidget(buy));}}
    private UiLayout.Rect panel(){UiLayout.Rect b=UiLayout.of(width,height).contentPanel();return new UiLayout.Rect(b.x(),b.y(),b.width(),Math.min(b.height(),Math.max(176,height-74)));}
    private Layout layout(UiLayout.Rect p){int pad=10,bodyY=p.y()+55,footer=25,bodyH=Math.max(90,p.height()-55-footer),gap=8,bodyW=p.width()-pad*2,listW=Math.max(150,(bodyW-gap)*58/100),detailW=bodyW-gap-listW,rowH=34,rows=Math.max(2,Math.min(7,bodyH/rowH));return new Layout(p.x()+pad,bodyY,listW,p.x()+pad+listW+gap,detailW,rowH,rows,p.y()+p.height()-23);}
    private List<ArenaClientShopItem> filtered(){return ClientShopStore.items().stream().filter(i->!HIDDEN.contains(i.id())).filter(i->!"Spectre DMR".equalsIgnoreCase(i.displayName())).filter(i->merged(i.category()).equals(category)).toList();}
    private static String merged(String c){if("SMG".equals(c))return"PISTOL";if("SNIPER".equals(c))return"RIFLE";if("SHOTGUN".equals(c))return"HEAVY";return c;}
    private static String label(String c){return switch(c){case"PISTOL"->"⌁ ПИСТОЛЕТЫ";case"RIFLE"->"◇ ВИНТОВКИ";case"HEAVY"->"◆ ТЯЖЁЛОЕ";default->c;};}
    @Override public void tick(){long s=ClientShopStore.resultSerial();if(s!=seen){seen=s;rebuild();}}
    @Override public void render(GuiGraphics g,int mx,int my,float pt){UiLayout.Rect p=panel();g.fill(0,0,width,height,0xB4080C15);g.fill(p.x()-3,p.y()-3,p.x()+p.width()+3,p.y()+p.height()+3,0x281F91A5);g.fill(p.x(),p.y(),p.x()+p.width(),p.y()+p.height(),0xF2111724);g.renderOutline(p.x(),p.y(),p.width(),p.height(),UiTheme.PANEL_BORDER);var snap=ClientSnapshotStore.get();g.drawString(font,Component.literal("✦ АРСЕНАЛ"),p.x()+10,p.y()+10,UiTheme.PINK);String money="$ "+snap.roundCredits();g.drawString(font,Component.literal(money),p.x()+p.width()-10-font.width(money),p.y()+10,UiTheme.ACCENT);g.fill(p.x()+10,p.y()+23,p.x()+p.width()-10,p.y()+24,UiTheme.GLOW);super.render(g,mx,my,pt);int pad=10,cy=p.y()+30,avail=p.width()-pad*2-(CATEGORIES.length-1)*5,cw=avail/CATEGORIES.length,cx=p.x()+pad;for(String c:CATEGORIES){if(c.equals(category)){g.fill(cx,cy+17,cx+cw,cy+18,UiTheme.ACCENT);g.renderOutline(cx,cy,cw,18,UiTheme.ACCENT);}cx+=cw+5;}Layout l=layout(p);List<ArenaClientShopItem> f=filtered();for(RowHit hit:rowHits){if(hit.index>=f.size())continue;ArenaClientShopItem it=f.get(hit.index);UiLayout.Rect r=hit.rect;boolean sel=hit.index==selectedIndex;g.fill(r.x(),r.y(),r.x()+r.width(),r.y()+r.height(),sel?0xE01A293D:0xB3101826);g.renderOutline(r.x(),r.y(),r.width(),r.height(),sel?UiTheme.HAIRLINE:0x402E3B50);if(sel)g.fill(r.x(),r.y(),r.x()+3,r.y()+r.height(),UiTheme.ACCENT);ItemStack st=itemStack(it);if(!st.isEmpty())g.renderItem(st,r.x()+7,r.y()+8);int tx=r.x()+30;g.drawString(font,Component.literal(fit(it.displayName(),r.width()-78)),tx,r.y()+6,UiTheme.TEXT);g.drawString(font,Component.literal("$"+it.price()),r.x()+r.width()-6-font.width("$"+it.price()),r.y()+6,UiTheme.GOLD);g.drawString(font,Component.literal(fit(WeaponNames.russianFor(it.id(),it.category()),r.width()-42)),tx,r.y()+18,UiTheme.MUTED);}if(!f.isEmpty())drawSelected(g,f.get(Math.min(selectedIndex,f.size()-1)),l);String result=ClientShopStore.resultMessage();if(!result.isBlank())g.drawString(font,Component.literal(fit(result,p.width()-20)),p.x()+10,p.y()+p.height()-12,ClientShopStore.resultOk()?UiTheme.GREEN:0xFFFF7373);}
    private void drawSelected(GuiGraphics g,ArenaClientShopItem it,Layout l){int cx=l.detailX+l.detailW/2,y=l.listY+5;g.fill(l.detailX,l.listY,l.detailX+l.detailW,l.buyY-4,0x48172233);g.renderOutline(l.detailX,l.listY,l.detailW,Math.max(20,l.buyY-l.listY-4),UiTheme.HAIRLINE);ItemStack st=itemStack(it);if(!st.isEmpty()){g.pose().pushPose();g.pose().translate(cx-16,y,100);g.pose().scale(2,2,2);g.renderItem(st,0,0);g.pose().popPose();}y+=38;g.drawCenteredString(font,Component.literal("◇ "+fit(it.displayName(),l.detailW-14)),cx,y,UiTheme.TEXT);y+=15;g.drawString(font,Component.literal("МАГ  "+it.magazineSize()+"   •   ЗАПАС  "+it.startingReserve()),l.detailX+5,y,UiTheme.MUTED);y+=13;g.drawString(font,Component.literal("РЕЖИМ  "+fit(it.fireModes(),Math.max(30,l.detailW-58))),l.detailX+5,y,UiTheme.DIM);}
    private ItemStack itemStack(ArenaClientShopItem it){ResourceLocation id=ResourceLocation.tryParse(it.id());if(id==null||!BuiltInRegistries.ITEM.containsKey(id))return ItemStack.EMPTY;var item=BuiltInRegistries.ITEM.get(id);return item==Items.AIR?ItemStack.EMPTY:new ItemStack(item);}
    private String fit(String t,int w){if(t==null||t.isBlank())return"—";if(font.width(t)<=w)return t;String e="…";return font.plainSubstrByWidth(t,Math.max(0,w-font.width(e)))+e;}
    @Override public boolean mouseScrolled(double mx,double my,double d){Layout l=layout(panel());if(new UiLayout.Rect(l.listX,l.listY,l.listW,l.rows*l.rowH).contains(mx,my)){int max=Math.max(0,(filtered().size()-1)/Math.max(1,l.rows)),old=page;if(d<0)page=Math.min(max,page+1);else if(d>0)page=Math.max(0,page-1);if(page!=old){rebuild();return true;}}return super.mouseScrolled(mx,my,d);}
    @Override public boolean keyPressed(int k,int s,int m){if(k==GLFW.GLFW_KEY_G||k==GLFW.GLFW_KEY_ESCAPE){onClose();return true;}return super.keyPressed(k,s,m);}
    @Override public void onClose(){if(minecraft!=null)minecraft.setScreen(null);}@Override public boolean isPauseScreen(){return false;}
    private record Layout(int listX,int listY,int listW,int detailX,int detailW,int rowH,int rows,int buyY){}private record RowHit(UiLayout.Rect rect,int index){}
}